### ISSUE TITLE
Early Voting Polling location geojson file property names differ from old one.

### ISSUE THREAD

**Issue by moczka** [codeforboston/cambridge_voting_locations#47]
After going over the code in module findPollingLocationsFor (polling_location_finder.js) I noticed that after the (lat, lng) coordinates from the user location are found in one of the Cambridge precincts (districts). The precinct code property name (.WardPrecinct) is used to find a polling location with the same precinct code (hence the nearest polling location). However, this property is missing in the Early Voting Polling location geojson file and a few key property names like pollingLocation.geojsonProperties.LOCATION, pollingLocation.geojsonProperties.Address changed so the module will not work with this new geojson unless we standardize the property names in both files. Since the early voting locations are just 5, I will be adding the percincts code manually and standardizing property names in both geojson files in my own fork of the project. I will also be working on adding the polling hours and other features I have in mind in a secondary branch.

**Comment by thecristen** [comment]
Does adding the precincts information to the early voting locations make sense? The early locations aren't associated with any particular precinct (so everyone can go to any early voting location to vote early). Though standardization still is a good idea. Typing this out makes me wonder if it might be better to have one geojson file for all voting locations, having some locations identifiable as 'early voting location' and others associated with specific ward/precinct. ....

Just some drive by thoughts.. :)

**Comment by moczka** [comment]
I think having them in one file could help. I didn't know in early voting you could go to any district. The thing is, the module that finds the closest poll relies on those precincts to find the closest poll. With that said, we need to find another way of finding the closest poll without relying on the precincts geojson. Also, I finished the module that controls the polling information hours in my own fork of the project. Do you think I can be added as a contributor and merge my with the master? I fetched any changes before working on that module. 

https://github.com/moczka/cambridge_voting_locations

**Comment by carpeliam** [comment]
Both sets of data, being GeoJSON, should conform to that standard if they don't already, but beyond that, I don't see a need right now for them to be in the same file or to share all the same properties - you actually don't want to use both sets of data at the same time. We shouldn't need to call `findPollingLocationFor` on the early voting locations, and I want to avoid drawing a false correlation or giving anyone the impression that that's where we want to go. (I also wouldn't want to maintain those properties if we don't ultimately end up using them.)

@moczka We follow a pull request model in order to make sure we're on the same page with the requirements and the functionality. If you issue a pull request from your fork, we can merge that in. I took a quick look, and there are a few things that we might need to talk about before a merge (I'm not sure if we did a good job outlining the requirements), but that's a conversation we can have in a PR.

**Comment by moczka** [comment]
Oh I see, I'm new to the code base and I was trying to make sense of it. It makes sense not to call findPolllingLocationFor early voting dates. I guess my confusion comes from the geoJson data in the /vendor folder and when it is used or not. Do you mind if we discuss that on slack? I  have opened the PR for the module I added.
