### ISSUE TITLE
bug: precinct of polling place differs from precinct shown

### ISSUE THREAD

**Issue by lucyq** [codeforboston/cambridge_voting_locations#57]
When searching for the polling location of 1654 Massachusetts Avenue, Cambridge, MA, the precinct for the displayed polling place is not the same as the one shown. This location happens to be on the border between two precincts. See screenshot!

<img width="744" alt="screen shot 2016-10-18 at 10 34 24 pm" src="https://cloud.githubusercontent.com/assets/6438622/19505378/0d6a3c52-9590-11e6-8f7c-64f5001f6438.png">

**Comment by moczka** [comment]
I found what was causing this bug. It seems the 28 Sacramento St. Cambridge MA is listed as the poll location for two precincts! The ward 7-1 and 7-2 both list "28 Sacramento St. Cambridge MA.

**Comment by carpeliam** [comment]
@thecristen I think you mentioned at some point that our geojson is sync'd with the Cambridge geojson, right? I wonder if there's an error in their data - https://www.cambridgema.gov/~/media/Files/electioncommission/mapsandpollinglocations/2016_PollingLocations.pdf?la=en definitely has different information for 7-1 and 7-2. I think we should update our geojson to be consistent with the cambridgema.gov site, and then check to see if Cambridge's data is up-to-date or not.

**Comment by moczka** [comment]
So after taking a closer look at the map. I think I figured something out. Cambridge is divided into wards numbered from 1 to 11. Those wards are subdivided into precincts labeled as "ward number - precinct number" i.e 7-1 and 7-2. So from the map, it seems Wards are not allowed to share polling locations but precincts are because they are part of one of the 11 wards. This bug also happens if you type 1 Rogers St Cambridge MA because precinct 1-1 doesn't have a polling location of its own.

**Comment by carpeliam** [comment]
yep - taking a closer look at the map, it looks like the polling location within the bounds of 7-2 actually belongs to 7-3. And even if the map is confusing, the table to the left of the map identifies the same location for 7-1 and 7-2. Closing this as invalid.

For future reference, https://github.com/cambridgegis/cambridgegis_data/blob/master/Elections/Polling_Locations/ELECTIONS_PollingLocations.geojson is Cambridge's source for polling locations.
